#!/usr/bin/bash

# Discover scripts/macros/ under the workspace, copy each bundle to
# $ROS2_PROJECTS_WS_ROOT/build_ws/macros/<repo>/, then source those copies.
# Usage: sync_macros

_sync_macros_repo_from_path() {
    # …/<repo>/scripts/macros → <repo>
    local macros_dir="$1"
    local scripts_dir
    scripts_dir="$(dirname "$macros_dir")"
    basename "$(dirname "$scripts_dir")"
}

_sync_macros_find_sources() {
    local root="$1"
    local src_root="${root}/src"
    local macros_dir

    if [[ -d "${root}/scripts/macros" ]]; then
        printf '%s\n' "${root}/scripts/macros"
    fi

    [[ -d "$src_root" ]] || return 0

    while IFS= read -r -d '' macros_dir; do
        printf '%s\n' "$macros_dir"
    done < <(
        find "$src_root" -maxdepth 12 -type d -path '*/scripts/macros' \
            -not -path '*/build/*' \
            -not -path '*/build_ws/*' \
            -not -path '*/install/*' \
            -not -path '*/log/*' \
            -not -path '*/.git/*' \
            -print0 2>/dev/null
    )
}

_sync_macros_extract_functions() {
    local file="$1"
    local line name
    while IFS= read -r line; do
        name="$(sed -E 's/^[[:space:]]*(function[[:space:]]+)?([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]*\(\).*/\2/' <<<"$line")"
        [[ "$name" == _* ]] && continue
        printf '%s\n' "$name"
    done < <(grep -E '^[[:space:]]*(function[[:space:]]+)?[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*\(\)' "$file" 2>/dev/null || true)
}

_sync_macros_copy_bundle() {
    local source_dir="$1"
    local dest_dir="$2"
    rm -rf "$dest_dir"
    mkdir -p "$dest_dir"
    cp -a "${source_dir}/." "$dest_dir/"
}

sync_macros() {
    local root="${ROS2_PROJECTS_WS_ROOT:-}"
    if [[ -z "$root" ]]; then
        echo "sync_macros: ROS2_PROJECTS_WS_ROOT is not set" >&2
        return 1
    fi

    local dest_root="${root}/build_ws/macros"
    mkdir -p "$dest_root"

    local -a sources=()
    local src
    while IFS= read -r src; do
        [[ -n "$src" ]] || continue
        sources+=("$src")
    done < <(_sync_macros_find_sources "$root")

    declare -A repo_from=()
    local -a ordered_repos=()
    local repo dest_dir file fn
    local collision=0

    for src in "${sources[@]}"; do
        repo="$(_sync_macros_repo_from_path "$src")"
        if [[ -n ${repo_from[$repo]:-} && ${repo_from[$repo]} != "$src" ]]; then
            echo "sync_macros: duplicate repo name '$repo':" >&2
            echo "  ${repo_from[$repo]}" >&2
            echo "  $src" >&2
            collision=1
            continue
        fi
        if [[ -z ${repo_from[$repo]:-} ]]; then
            ordered_repos+=("$repo")
        fi
        repo_from[$repo]="$src"
    done

    declare -A fn_from=()
    local -a index_lines=()
    index_lines+=("# generated by sync_macros")
    index_lines+=("# repo	source	file	function")

    for repo in "${ordered_repos[@]}"; do
        src="${repo_from[$repo]}"
        dest_dir="${dest_root}/${repo}"
        shopt -s nullglob
        local -a bash_files=( "$src"/*.bash )
        shopt -u nullglob
        for file in "${bash_files[@]}"; do
            while IFS= read -r fn; do
                [[ -n "$fn" ]] || continue
                if [[ -n ${fn_from[$fn]:-} ]]; then
                    echo "sync_macros: duplicate function '$fn':" >&2
                    echo "  ${fn_from[$fn]}" >&2
                    echo "  ${src}/$(basename "$file")" >&2
                    collision=1
                    continue
                fi
                fn_from[$fn]="${src}/$(basename "$file")"
                index_lines+=("${repo}	${src}	$(basename "$file")	${fn}")
            done < <(_sync_macros_extract_functions "$file")
        done
    done

    if [[ "$collision" -eq 1 ]]; then
        echo "sync_macros: aborted (fix name collisions, then run sync_macros again)" >&2
        return 1
    fi

    local existing
    shopt -s nullglob
    for existing in "$dest_root"/*/; do
        repo="$(basename "$existing")"
        [[ -n ${repo_from[$repo]:-} ]] && continue
        rm -rf "$existing"
    done
    shopt -u nullglob

    for repo in "${ordered_repos[@]}"; do
        src="${repo_from[$repo]}"
        dest_dir="${dest_root}/${repo}"
        _sync_macros_copy_bundle "$src" "$dest_dir"
    done

    printf '%s\n' "${index_lines[@]}" > "${dest_root}/macros_index"

    local had_nounset=0
    if [[ $- == *u* ]]; then
        had_nounset=1
        set +u
    fi
    shopt -s nullglob
    for file in "${dest_root}"/*/*.bash; do
        source "$file"
    done
    shopt -u nullglob
    if [[ "$had_nounset" -eq 1 ]]; then
        set -u
    fi
}
