#!/usr/bin/bash

# Discover scripts/macros/ under the workspace, copy each bundle to
# $ROS2_PROJECTS_WS_ROOT/build_ws/macros/<repo>/, then source those copies.
# Usage: sync_macros

_macros_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${_macros_dir}/helpers/helpers_list.bash"
unset _macros_dir

sync_macros() {
    if ! sync::_has_workspace_root; then
        echo "sync_macros: ROS2_PROJECTS_WS_ROOT is not set" >&2
        return 1
    fi

    local root="${ROS2_PROJECTS_WS_ROOT}"
    local dest_root
    dest_root="$(sync::_get_dest_root)"
    mkdir -p "$dest_root"

    local -a sources=()
    local src
    while IFS= read -r src; do
        [[ -n "$src" ]] || continue
        sources+=("$src")
    done < <(sync::_find_sources "$root")

    declare -A repo_from=()
    local -a ordered_repos=()
    local repo dest_dir file fn
    local collision=0

    for src in "${sources[@]}"; do
        repo="$(sync::_get_repo_from_path "$src")"
        if [[ -n ${repo_from[$repo]:-} && ${repo_from[$repo]} != "$src" ]]; then
            echo "sync_macros: duplicate repo name '$repo':" >&2
            echo "  ${repo_from[$repo]}" >&2
            echo "  $src" >&2
            collision=1
            continue
        fi
        if [[ -z ${repo_from[$repo]:-} ]]; then
            ordered_repos+=("$repo")
        fi
        repo_from[$repo]="$src"
    done

    declare -A fn_from=()
    local -a index_lines=()
    index_lines+=("# generated by sync_macros")
    index_lines+=("# repo	source	file	function")

    for repo in "${ordered_repos[@]}"; do
        src="${repo_from[$repo]}"
        dest_dir="${dest_root}/${repo}"
        shopt -s nullglob
        local -a bash_files=()
        if [[ -d "${src}/api" ]]; then
            bash_files=( "$src"/api/*.bash )
        else
            # Backward compatible: flat scripts/macros/*.bash
            bash_files=( "$src"/*.bash )
        fi
        shopt -u nullglob
        for file in "${bash_files[@]}"; do
            while IFS= read -r fn; do
                [[ -n "$fn" ]] || continue
                if [[ -n ${fn_from[$fn]:-} ]]; then
                    echo "sync_macros: duplicate function '$fn':" >&2
                    echo "  ${fn_from[$fn]}" >&2
                    echo "  ${src}/$(basename "$file")" >&2
                    collision=1
                    continue
                fi
                fn_from[$fn]="${src}/$(basename "$file")"
                index_lines+=("${repo}	${src}	$(basename "$file")	${fn}")
            done < <(sync::_extract_functions "$file")
        done
    done

    if [[ "$collision" -eq 1 ]]; then
        echo "sync_macros: aborted (fix name collisions, then run sync_macros again)" >&2
        return 1
    fi

    local existing
    shopt -s nullglob
    for existing in "$dest_root"/*/; do
        repo="$(basename "$existing")"
        [[ -n ${repo_from[$repo]:-} ]] && continue
        rm -rf "$existing"
    done
    shopt -u nullglob

    for repo in "${ordered_repos[@]}"; do
        src="${repo_from[$repo]}"
        dest_dir="${dest_root}/${repo}"
        sync::_copy_bundle "$src" "$dest_dir"
    done

    printf '%s\n' "${index_lines[@]}" > "${dest_root}/macros_index"
    sync::_source_cache "$dest_root"
}
